### ISSUE TITLE
react emot

### ISSUE THREAD

**Issue by dean-fahreza** [bellshade/wpu_bot#27]
tambahin react "ga nanya dan ga peduli" yg sempet jadi memes di facebook :3 kek [ini](https://www.google.com.sg/search?q=ga+peduli+ga+nanya+meme&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiumNjnpbj1AhUzT2wGHXB3ASgQ_AUoAXoECAEQAw&biw=1536&bih=714&dpr=1.25)

**Comment by dhafitf** [comment]
Bisa langsung kontribusi ke [sticker.json](https://github.com/bellshade/wpu_bot/blob/main/data/sticker.json) dengan mengirimkan pull request yang sesuai dengan [CONTRIBUTING.md](https://github.com/bellshade/wpu_bot/blob/main/CONTRIBUTING.md).

**Comment by dean-fahreza** [comment]
behh sipp :333
