### ISSUE TITLE
fitur game

### ISSUE THREAD

**Issue by rulanugrh** [bellshade/wpu_bot#29]
sedikit tambahan aja si om, adain fitur game biar enak aja gitu , contohnya kaya game scripting gitu atau solving code

**Comment by LevianthProject** [comment]
Halo thank you atas sarannya tapi sepertinya untuk saat ini saya belum bisa menerima saran ini untuk dijadikan fitur di wpubot, 
mungkin nanti bisa dijadikan ide inovasi baru jika kita memerlukan ide untuk fitur fitur yang ingin dan bisa ditambahkan di wpubot 👍🏻 

**Terima kasih atas sarannya!**
-Levianth

**Comment by rulanugrh** [comment]
siap makasih om
