### ISSUE TITLE
update system point : add more point & add reason 

### ISSUE THREAD

**Issue by LevianthProject** [bellshade/wpu_bot#30]
### feature update
Point system count point more than 100 point

### add feature 
Add reason when `;addpoint` & `;decpoint`
example: 
`;addpoint @/users 1 {reason} events` & `;decpoint @/users 1 {reason} bad attitude`

**Comment by dhafitf** [comment]
Point bisa lebih dari 100.
Namun jika menambah/mengurangi point pada user yang belum terdaftar pada database, maka akan dilakukan pembuatan data terlebih dahulu.
https://github.com/bellshade/wpu_bot/blob/b7c0c656ed8950c313b2f38eb7e3a22ec40cc658/modules/point-system.js#L101-L117
Kode di atas diartikan sebagai: "Temukan data ketua menggunakan id milik ketua, jika ditemukan pada database, maka update data yang ada. Namun jika tidak ditemukan, maka buat baru dengan default point 1".

Masalah ini mungkin bisa diatasi dengan mengganti default point pada kode.

Namun untuk menambah reason, mungkin perlu didiskusikan terlebih dahulu, karena juga mempertimbangkan issues #24
