### ISSUE TITLE
Fix sticker auto triggered when mentioned

### ISSUE THREAD

**Issue by dipras** [bellshade/wpu_bot#34]
Setiap kali menggunakan nama sticker yang bersangkutan, sticker akan terkirim secara otomatis dan menghapus kata yang seharusnya ingin di sampaikan. Perlu sebuah tambahan suatu symbol pada text nya agar user jelas ingin menggunakan sticker atau tidak

**Comment by manh21** [comment]
sebenarnya sticker nya itu sudah ada prefix `:` kemudian di ikuti keyword bisa dilihat di data ini
https://github.com/bellshade/wpu_bot/blob/c85e0d7708d06d44da4a8a9e6289883f3aa6ab32/data/sticker.json#L1-L38

tetapi pada pull request #31 dan #33 tidak ada prefix `:`
begitu penjelasannya
