### ISSUE TITLE
stiker batu

### ISSUE THREAD

**Issue by rulanugrh** [bellshade/wpu_bot#41]
**Name of the sticker**
membatu

**Sticker image/gif url**
https://media.discordapp.net/attachments/912962440315174973/933640317352181831/43722754-b168-4162-981e-db35e1cdf1fd.png

**Additional context**
context : buat bingung nyari topik / apapun itu yang terhbung dengan stiker batu

**Comment by manh21** [comment]
Mau buat Pull Request?

**Comment by rulanugrh** [comment]
boleh aja om kalau diizinkan
nanti ku tinggal tambahin di stiker.json kan jika diperkenankan?

**Comment by manh21** [comment]
Iya

> boleh aja om kalau diizinkan nanti ku tinggal tambahin di stiker.json kan jika diperkenankan?

**Comment by rulanugrh** [comment]
oke om aku mau pull request
