### ISSUE TITLE
Error message ketika check permission

### ISSUE THREAD

**Issue by dhafitf** [bellshade/wpu_bot#8]
![Screenshot_1188](https://user-images.githubusercontent.com/87353624/148636009-932a55f3-f2a5-4332-a41e-82d4eafaba48.png)
https://github.com/bellshade/wpu_bot/blob/b22afe5316a3abc67941113c85e923896384fd28/modules/timeout.js#L50
Bisa ngetimeout ketika kode di atas, diganti dengan ini
```js
if (await checkPermission(msg, guildMember)) return;
```
Namun tetap ngirim error message

![Screenshot_1189](https://user-images.githubusercontent.com/87353624/148636536-2ac9b33d-288b-48f7-b6f4-8f9bcd5e09e8.png)

**Comment by manh21** [comment]
disini check apakah user memiliki role yang lebih tinggi dan apakah punya role dan apakah user yang dimention merupakan server owner. jadi kalau kondisi tersebut tidak terpenuhi maka akan return false dan mengirim error.
https://github.com/bellshade/wpu_bot/blob/b22afe5316a3abc67941113c85e923896384fd28/modules/utility.js#L109-L119

Mengatasi error:
* Buat role untuk bot
* pastikan role tersebut berada di atas semua role/user yang ingin di beri timeout

Berhasil dengan baik tanpa error
![image](https://user-images.githubusercontent.com/31276236/148643783-7edf4aad-4c90-43ea-ab2a-98a9ab1bd603.png)

Permission level working correctly
![image](https://user-images.githubusercontent.com/31276236/148643820-100c5813-e3a5-4108-bace-61c8f396cfcc.png)

**Comment by dhafitf** [comment]
Okay solved
